%{
    #include <iostream>
    using namespace std;
    #include "source.hpp"
    #define YYSTYPE Node*
    extern int yylex();
    void yyerror(const char*);
%}

%token RELOP
%token NUM

%%
S:      A   {printf("S to A\n");}
;
A:      NUM {printf("NUM mm\n");}
    |   RELOP {printf("RELOP\n");}
;
%%
/*Cpp functions*/
void yyerror(const char*) {
    cout << "syntax error" << endl;
}

int main() {
    return yyparse();
}

